export const SAVE_INCOME_REQUEST = "SAVE_INCOME_REQUEST";
export const FETCH_INCOME_REQUEST = "FETCH_INCOME_REQUEST";
export const UPDATE_INCOME_REQUEST = "UPDATE_INCOME_REQUEST";
export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const INCOME_SUCCESS = "INCOME_SUCCESS";
export const INCOME_FAILURE = "INCOME_FAILURE";